### ISSUE TITLE
Missing class when using Paper 1.20.6

### ISSUE THREAD

**Issue by maurxce** [TriumphTeam/triumph-gui#114]
Hello,
this repo hasn't gotten any updates in 2 months, is it still being worked on? It seems the library does not work with 1.20.6 at this moment:
```
[18:48:29 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftMetaItem
[18:48:29 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[18:48:29 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[18:48:29 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[18:48:29 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[18:48:29 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[18:48:29 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[18:48:29 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[18:48:29 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.gui.components.util.VersionHelper.craftClass(VersionHelper.java:136)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.gui.builder.item.BaseItemBuilder.<clinit>(BaseItemBuilder.java:77)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.utils.GuiItemBuilder.build(GuiItemBuilder.java:78)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.configuration.GUIConfig.getFiller(GUIConfig.java:37)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.gui.RewardsGUI.setFiller(RewardsGUI.java:107)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.gui.RewardsGUI.lambda$addDefaultItems$3(RewardsGUI.java:81)
[18:48:29 WARN]:        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.gui.RewardsGUI.addDefaultItems(RewardsGUI.java:79)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.gui.RewardsGUI.insertItems(RewardsGUI.java:73)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.gui.RewardsGUI.open(RewardsGUI.java:67)
[18:48:29 WARN]:        at SpelerLevels-1.3.8 (2).jar//dev.maurxce.spelerlevels.commands.RewardCommand.onCommand(RewardCommand.java:54)
[18:48:29 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:48:29 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86)
[18:48:29 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[18:48:29 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
[18:48:29 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[18:48:29 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[18:48:29 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[18:48:29 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[18:48:29 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:450)
[18:48:29 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:357)
[18:48:29 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:344)
[18:48:29 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:339)
[18:48:29 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2282)
[18:48:29 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2256)
[18:48:29 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:48:29 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[18:48:29 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[18:48:29 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1552)
[18:48:29 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198)
[18:48:29 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[18:48:29 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1529)
[18:48:29 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1452)
[18:48:29 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[18:48:29 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1418)
[18:48:29 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279)
[18:48:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[18:48:29 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by LichtHund** [comment]
Yes it is being worked on. 1.16.6 support will be available as soon as adventure bukkit platform is updated.
