### ISSUE TITLE
ERROR: The name of the profile is longer than 16 characters

### ISSUE THREAD

**Issue by 0PandaDEV** [TriumphTeam/triumph-gui#119]
This error occurs upon trying to open a normal chest GUI.

```zsh
[20:42:48 ERROR]: Command exception: /m
org.bukkit.command.CommandException: Unhandled exception executing command 'm' in plugin Nextron v1.5.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:28) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.commands.execution.CommandQueueEntry.action(CommandQueueEntry.java:5) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:450) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:359) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:349) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:344) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2317) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2291) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1526) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:184) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1504) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1432) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1397) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:312) ~[leaf-1.20.6.jar:1.20.6-DEV-599bfa2]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: The name of the profile is longer than 16 characters
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-33.2.0-jre.jar:?]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:67) ~[?:?]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:76) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:138) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:708) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:63) ~[?:?]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[?:?]
        at Nextron-1.5.5.jar/dev.triumphteam.gui.guis.BaseGui.populateGui(BaseGui.java:981) ~[Nextron-1.5.5.jar:?]
        at Nextron-1.5.5.jar/dev.triumphteam.gui.guis.BaseGui.open(BaseGui.java:436) ~[Nextron-1.5.5.jar:?]
        at Nextron-1.5.5.jar/net.pandadev.nextron.guis.GUIs.mainGui(GUIs.java:86) ~[Nextron-1.5.5.jar:?]
        at Nextron-1.5.5.jar/net.pandadev.nextron.commands.MenuCommand.execute(MenuCommand.java:26) ~[Nextron-1.5.5.jar:?]
        at Nextron-1.5.5.jar/net.pandadev.nextron.commands.CommandBase.onCommand(CommandBase.java:50) ~[Nextron-1.5.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more
```

This is the code block that is throwing the error

```java
public static void mainGui(Player player) {
        Gui gui = Gui.gui()
                .title(Component.text("Menu"))
                .disableAllInteractions()
                .rows(5)
                .create();

        gui.setItem(3, 3, ItemBuilder.skull(Utils.createSkull("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWMyZmYyNDRkZmM5ZGQzYTJjZWY2MzExMmU3NTAyZGM2MzY3YjBkMDIxMzI5NTAzNDdiMmI0NzlhNzIzNjZkZCJ9fX0=")).name(Component.text("§fSettings")).asGuiItem(inventoryClickEvent -> {
            playerSettings(player);
        }));

        gui.setItem(2, 5, ItemBuilder.from(Material.COMPASS).name(Component.text("§7Home Manager")).asGuiItem(inventoryClickEvent -> {
            if (!Configs.feature.getBoolean("home_system")) {
                player.sendMessage(Main.getPrefix() + Text.get("maingui.disabled.homes"));
                return;
            }
            if (Configs.home.getConfigurationSection("Homes." + player.getUniqueId()) == null || Configs.home
                    .getConfigurationSection("Homes." + player.getUniqueId()).getKeys(false).isEmpty()) {
                player.sendMessage(Main.getPrefix() + Text.get("maingui.no.homes"));
                player.playSound(player.getLocation(), Sound.ENTITY_PILLAGER_AMBIENT, 100, 0.5f);
            } else {
                HomeGUIs.manager(player);
            }
        }));

        gui.setItem(4, 5, ItemBuilder.from(Material.RECOVERY_COMPASS).name(Component.text("§x§2§9§d§f§e§bWarp Manager")).asGuiItem(inventoryClickEvent -> {
            if (!Configs.feature.getBoolean("warp_system")) {
                player.sendMessage(Main.getPrefix() + Text.get("maingui.disabled.warps"));
                return;
            }
            if (Configs.warp.getConfigurationSection("Warps") == null || Configs.warp.getConfigurationSection("Warps").getKeys(false).isEmpty()) {
                player.sendMessage(Main.getPrefix() + Text.get("maingui.no.warps"));
                player.playSound(player.getLocation(), Sound.ENTITY_PILLAGER_AMBIENT, 100, 0.5f);
            } else {
                WarpGUIs.manager(player);
            }
        }));

        if (player.hasPermission("nextron.rank")) {
            gui.setItem(3, 7, ItemBuilder.from(Material.NAME_TAG).name(Component.text("§x§2§9§d§f§e§bRank Manager")).asGuiItem(inventoryClickEvent -> {
                if (!Configs.feature.getBoolean("rank_system")) {
                    player.sendMessage(Main.getPrefix() + Text.get("maingui.disabled.ranks"));
                    return;
                }
                if (Main.getInstance().getConfig().getConfigurationSection("Ranks") == null || Main
                        .getInstance().getConfig().getConfigurationSection("Ranks").getKeys(false).isEmpty()) {
                    player.sendMessage(Main.getPrefix() + Text.get("maingui.no.ranks"));
                    player.playSound(player.getLocation(), Sound.ENTITY_PILLAGER_AMBIENT, 100, 0.5f);
                } else {
                    RankGUIs.manager(player);
                }
            }));
        } else {
            gui.setItem(3, 7, ItemBuilder.from(Material.BARRIER).name(Component.text(Text.get("no.perms"))).asGuiItem());
        }

        if (player.hasPermission("nextron.features")) {
            gui.setItem(5, 1, ItemBuilder.from(Material.REDSTONE).name(Component.text("§4Feature Manager")).asGuiItem(inventoryClickEvent -> {
                featureGui(player);
            }));
        } else {
            gui.setItem(5, 1, ItemBuilder.from(Material.BARRIER).name(Component.text(Text.get("no.perms"))).asGuiItem());
        }

        gui.open(player);
    }
```

Entire source code is [here](https://github.com/0PandaDEV/Nextron/blob/master/src/main/java/net/pandadev/nextron/guis/GUIs.java)

**Comment by LichtHund** [comment]
Apologies, I didn't see this issue. That error seems to be coming from the ItemStack created by your util class, since it doesn't take into account some changes made to GameProfile recently. Using the built in method worked perfectly fine for me, `ItemBuilder.skull().texture("eyJ0ZXh0dXJlcy...")...`.

**Comment by 0PandaDEV** [comment]
thanks i will try this
