### ISSUE TITLE
Errors If you use it on many plugins

### ISSUE THREAD

**Issue by Kr1S-D** [TriumphTeam/triumph-gui#55]
I am using this lib to simplify my work for my server, however I have noticed that for some strange reason most of the time some plugins fail on other plugins.
Ex: I have my "crystalmobarena" plugin which has a GUI I will click on and for some strange reason (as seen in the error) the "rubyutils" plugin will give an error containing the stacktrace of another plugin.
This all happens randomly and can be fixed by restarting the server, but I don't think this is normal!
I have about 4/5 plugins on my server that use this library
Error:
```
[19:49:36 ERROR]: Could not pass event InventoryClickEvent to RubyUtils v3.3.10
java.lang.NoSuchMethodError: dev.triumphteam.gui.builder.item.ItemBuilder.setName(Ljava/lang/String;)Ldev/triumphteam/gui/builder/item/BaseItemBuilder;
        at me.kr1s_d.crystalmobarena.creator.gui.ArenaEditorPanel.build(ArenaEditorPanel.java:83) ~[?:?]
        at me.kr1s_d.crystalmobarena.creator.gui.ArenaEditorPanel.<init>(ArenaEditorPanel.java:48) ~[?:?]
        at me.kr1s_d.crystalmobarena.creator.gui.ArenaSelectorPanel.lambda$build$3(ArenaSelectorPanel.java:76) ~[?:?]
        at dev.triumphteam.gui.guis.GuiListener.onGuiClick(GuiListener.java:102) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1002.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

**Comment by ipsk** [comment]
Hello, yes this is common with any lib you use, that is why it is suggested that you relocate the libraries.
On the setup page on the docs there is a guide in the bottom (mave or gradle) on how to relocate https://mf.mattstudios.me/triumph-gui/setup-1.

**Comment by Kr1S-D** [comment]
Should I relocate it to the main plugin class? or for each class that uses a gui?

**Comment by ipsk** [comment]
You'd relocate the packages to the main package of your plugin, for example, from `dev.triumphteam.gui` to `my.package.plugin.gui`.

**Comment by Kr1S-D** [comment]
like this:

```

<configuration>
                    <relocations>
                        <relocation>
                            <pattern>dev.triumphteam.gui</pattern>
                            <shadedPattern>me.kr1s_d.crystalmobarena.creator.gui</shadedPattern> <!-- Replace package here here -->
                        </relocation>
                    </relocations>
                </configuration>
```

**Comment by Kr1S-D** [comment]
like this? 
https://pastebin.com/TpfA9AuD

**Comment by ipsk** [comment]
Yeah! ;p

**Comment by Kr1S-D** [comment]
ok Thx you ;D
